stages:
  - lint
  - test

lint_biome:
  stage: lint
  image: node:20 # Assuming Biome requires Node.js, adjust as necessary
  script:
    - npm ci # Install dependencies if needed
    - npm run lint # Run linter
  only:
    - branches

jest_test:
  stage: test
  image: node:20
  script:
    - npm ci
    - npm run test
  only:
    - branches