stages:
  - lint
  - test

lint_biome:
  stage: lint
  image: harbor.pg.innopolis.university/docker-hub-cache/node:20
  script:
    - npm ci # Install dependencies if needed
    - npm run lint # Run linter
  only:
    - branches

jest_test:
  stage: test
  image: harbor.pg.innopolis.university/docker-hub-cache/node:20
  script:
    - npm ci
    - npm run test
  only:
    - branches
