stages:
  - lint
  - test

lint_biome:
  stage: lint
  image: node:latest # Assuming Biome requires Node.js, adjust as necessary
  script:
    - npm ci # Install dependencies if needed
    - npm run lint # Run linter
  only:
    - branches

jest_test:
  stage: test
  image: node:latest
  variables:
    GOOGLE_APPLICATION_CREDENTIALS: "creds.json"
  script:
    - npm ci
    - npm install firebase-tools -g
    - echo $GOOGLE_APPLICATION_CREDENTIALS
    - echo "$GOOGLE_CREDENTIALS" | base64 --decode > creds.json
    - cat creds.json
    - firebase init emulators
    - npm run test
  only:
    - branches