stages:
  - lint
  - test

lint_biome:
  stage: lint
  image: node:latest # Assuming Biome requires Node.js, adjust as necessary
  script:
    - npm ci # Install dependencies if needed
    - npm run lint # Run linter
  only:
    - branches

jest_test:
  stage: test
  image: node:latest
  script:
    - apt-get update
    - apt-get install -y openjdk-11-jdk
    - npm ci
    - npm install firebase-tools -g
    - firebase login
    - firebase emulators:start
    - npm run test
  only:
    - branches