ADMINS_DB = "admins/";
SESSIONS_DB = "sessions/";
SESSION_TIMEOUT = 600_000;
VECTOR_DB_UPDATE_FREQUENCY = 20 * 60 * 1000;

module.exports = {
	ADMINS_DB,
	SESSIONS_DB,
	SESSION_TIMEOUT,
	VECTOR_DB_UPDATE_FREQUENCY,
};
